### ISSUE TITLE
Directory comparison

### ISSUE THREAD

**Issue by alishahb** [AlexIljin/regexPreFilter#1]
Is it posible add to this functionality to work in directory comparison?
I want to ignore comparison of all using and namespace lines in C# *.cs files , it works with your plugin with regex rules for file-file comparison, but won't  work for directory comparison

``^using .*;$
``
``^namespace .*$``

Or maybe you can suggest how to make it works?

Thank you!

**Comment by alex-ilin** [comment]
Unfortunately, WinMerge doesn't support what you wish. If you want, you can hack into their code to add that as a new feature: https://sourceforge.net/projects/winmerge/files/stable/2.14.0/WinMerge-2.14.0-src.7z/download
Sorry I couldn't be of more help to you.
